#!/bin/bash
module purge
module load openmpi/4.0.2
module load intel-compiler/2020.0.166
module load netcdf/4.7.1

code_root=/home/156/jm5970/expts/mitgcm_offline_flt/code
dir_root=/g/data4/x77/jm5970/MITgcm

cd /home/156/jm5970/expts/mitgcm_offline_flt/build 

rm -r *

# ../../../../models/MITgcm/tools/genmake2 -mods=../code -rootdir /home/156/jm5970/models/MITgcm -mpi

conf_file=../linux_amd64_ifort_gadi

${dir_root}/tools/genmake2 -mods=${code_root} -rootdir ${dir_root} -optfile ${conf_file} -mpi

#make depend
#make -j 8
