ncpus: 1
mem: 44GB
walltime: 04:00:00
jobname: PR_LAV_{0}
project: x77
queue: normal

storage:
      gdata:
          - v45

model: mitgcm
shortpath: /scratch/x77
exe: mitgcm_HR_satellite_P_release
input: global_particle_release/30d/30d_slice_chunk_{0}

runlog: False

collate: True
userscripts:
  archive: clear_archive.sh

