ncpus: 128
mem: 300GB
walltime: 03:00:00
jobname: PR_LAV_{0}
project: v45
queue: express

model: mitgcm
shortpath: /short/v45
exe: mitgcm_HR_satellite_P_release
input: 30d_slice_chunk_{0}

#collate: True
#collate_walltime: 1:00:00
#collate_mem: 1GB
