ncpus: 96
mem: 300GB
walltime: 03:00:00
jobname: PR_LAV_00006
project: x77
queue: express
qsub_flags: -lother=hyperthread -W umask=027 -l storage=gdata/v45+scratch/v45+gdata/hh5+gdata/x77

model: mitgcm
shortpath: /scratch/x77
exe: mitgcm_HR_satellite_P_release
input: global_particle_release/30d/30d_slice_chunk_00006

#collate: True
#collate_walltime: 1:00:00
#collate_mem: 1GB
userscripts:
  archive: clear_archive.sh

