format: yamanifest
version: 1.0
---
work/flt_global_hex_010deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_010deg.bin
  hashes:
    binhash: 003e2910dd6bfba3f842195f4beef210
    md5: 381c9c554792c8ef904f0bba444ad7b9
work/flt_global_hex_012deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_012deg.bin
  hashes:
    binhash: b8cab15390e154a68e4fc5ecac3b4f82
    md5: 1cc0fef6014cfa8cd0673b8aacdd0679
work/flt_global_hex_015deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_015deg.bin
  hashes:
    binhash: b6cc4b9e19d23ee98a4dd262773de4cd
    md5: c7cf357c33562a5506c9e558c50016ba
work/flt_global_hex_032deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_032deg.bin
  hashes:
    binhash: 683f0579cf33d2c48619f0212adab07e
    md5: 2364279001da74370a495ad32f9bfd75
work/flt_global_hex_05deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_05deg.bin
  hashes:
    binhash: 20ce81b77dbcd036904e59b358526d17
    md5: c41b011f83fbcf62964f5ba427988fb2
work/flt_global_hex_10deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_10deg.bin
  hashes:
    binhash: 280841a469fc6a39ef3beaaceb5daf80
    md5: eced84b25da947aef352c9fb34460e14
work/flt_global_hex_1deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_1deg.bin
  hashes:
    binhash: 6ace25cb3a3ccded733687ad7ad06821
    md5: a0fdcbc15ee5822b4b1bd096df090aae
work/flt_global_hex_5deg.bin:
  fullpath: /scratch/x77/jm5970/mitgcm/input/global_particle_release/flt_global_hex_5deg.bin
  hashes:
    binhash: 67c13cd9c1abb86d5c638b415c7cbee0
    md5: 3700f8fa95bb2c55bd71fd09f587a6bf
