ncpus: 128
mem: 300GB
walltime: 03:00:00
jobname: PR_LAVD_00000
project: v45
queue: express

model: mitgcm
shortpath: /short/v45
exe: mitgcm_HR_satellite_P_release
input: global_particle_release/30d/30d_slice_chunk_00000

#for normalbw
# platform:
#    nodesize: 32

userscripts:
   archive: clear_archive.sh

# collate: True
# collate_walltime: 1:00:00
# collate_mem: 1GB
