ncpus: 1
mem: 10GB
walltime: 02:00:00
jobname: MIT_LAVD
project: x77
queue: express
storage:
      gdata:
          - v45

model: mitgcm
shortpath: /scratch/x77
exe: mitgcm_HR_satellite_P_release
input: global_particle_release

#collate: True
#collate_walltime: 1:00:00
#collate_mem: 1GB
